### ISSUE TITLE
video library can not be downloaded in processing 3

### ISSUE THREAD

**Issue by lhcui** [processing/processing-video#15]
After click the Install, Downloading is going on, but in very slow speed. After several minutes, it fails. I've tried several different proxy configurations for better downloading performance which don't work all.

**Comment by mplatnic** [comment]
I tried to download the library with Processing 3.0a5 on Raspberry (linux32) with Jdk8, it worked. But then when I tried to run my program (that ran perfectly before on windows with P2.2.1) 
I got: "Cannot parse error text: annotation processing got disabled since it requires 1.6 compliant JVM"
can i be linked to the library?
Thanks

**Comment by loserr1235** [comment]
me too, and the sound library has the same problem . I try to use the source code but it can't be installed

**Comment by codeanticode** [comment]
@loserr1235 I tried installing both the video and the sound library using the 3.0 release (no betas or alphas), and didn't observe any issue. What version of Processing are you using, and what OS are you on?

**Comment by codeanticode** [comment]
@loserr1235 @mplatnic @lhcui Is anyone having any installation issues with the video library in Processing 3.0 (final)? If not, I will go ahead and close this issue.

**Comment by loserr1235** [comment]
@codeanticode  I tried the final ver, now I can install the libraries. But when I run the example from the sound libraries ,it crushed like this
![2015-10-03_141625](https://cloud.githubusercontent.com/assets/13272256/10261765/5c39796c-69d9-11e5-8f03-77e3ab66bed4.jpg)
I don't know how to solve it, though I find many others have the same problem
By the way , I can't get access to the Processing official website today ,but I think it is because I am in China Mainland

**Comment by REAS** [comment]
@loserr1235 Sound libraries issues should go into processing/processing-sound It seems like people are able to download the Video library, so I'm closing this one.

**Comment by vwls** [comment]
This issue persists (processing version 3.0.1)

Was working with a student in China today who was experiencing the above problem using the video library. Removing non-ascii characters (in this case, chinese characters) from all file paths solved it. 

See related issue: 
https://github.com/processing/processing/issues/2472

**Comment by e-e-e** [comment]
I have also encountered this issue - Running OSX 10.10.5 with Processing 3.3.6.

**Comment by benfry** [comment]
(Locking this two year old issue that's since been resolved… If you have a problem, please file a new bug.)
