### ISSUE TITLE
need to start processing from command line to get video

### ISSUE THREAD

**Issue by bwanaaa** [processing/processing-video#177]
I read about some other people having trouble with processing on the Mac and the recommendation is to update the video library. I downloaded the most recent beta (2.0 beta 5) from here:
https://github.com/processing/processing-video/releases/tag/latest

I followed this:

http://wiki.iad.zhdk.ch/CV/904626177/Video+Library+2.0

and

now in order to start processing I always have to use terminal and enter

/Applications/Processing.app/Contents/MacOS/Processing

Is there a way to make this more user friendly?

**Comment by marcobrianza** [comment]
yes, same problem here.

**Comment by doronby** [comment]
I get 

UnsatisfiedLinkError: Could not load library: gstreamer
UnsatisfiedLinkError: Could not load library: gstreamer
A library relies on native code that's not available.
Or only works properly when the sketch is run as a 32-bit application.
UnsatisfiedLinkError: Could not load library: gstreamer
UnsatisfiedLinkError: Could not load library: gstreamer

**Comment by lub34** [comment]
@doronby Yo, did you ever figure out a solution to your issue? I'm having a similar problem

**Comment by bwanaaa** [comment]
unfortunately not.

**Comment by benfry** [comment]
Try using Processing 4.0 alpha 5 (or later) https://github.com/processing/processing4/releases

**Comment by doronby** [comment]
Nothing works for me...:(

	-----------------------------------------From: "lub34" 
To: "processing/processing-video"
Cc: "doron", "Mention"
Sent: Tuesday July 6 2021 10:02:45AM
Subject: Re: [processing/processing-video] need to start processing
from command line to get video (#177)

	@doronby [1] Yo, did you ever figure out a solution to your issue?
I'm having a similar problem 

	—
 You are receiving this because you were mentioned.
 Reply to this email directly,  view it on GitHub [2], or  unsubscribe
[3]. 

Links:
------
[1] https://github.com/doronby
[2]
https://github.com/processing/processing-video/issues/177#issuecomment-874787717
[3]
