### ISSUE TITLE
Get source frame rate or number of frames

### ISSUE THREAD

**Issue by krismz** [processing/processing-video#19]
I need to be able to step frame by frame through a video.  Can you provide an interface that either lets me get the source frame rate (so I can convert from seconds to frames and back), or a method that provides the total number of frames, so that I can calculate the frame rate.  I'd actually prefer the latter, plus a jump method that could take a frame number, but either approach will let me switch between frames and seconds.  Thanks!

**Comment by krismz** [comment]
Yes, that worked for me, thanks!  But it seems that frameRate is always the current playing frame rate of the movie which is only the same thing as the original frame rate prior to any sort of call to movie.frameRate(some_other_frame_rate).  Is this true?  If I want to skip to a specific frame in a movie, I need to jump based on the original source frame rate, not the current playing frame rate.  I'm handling this now by saving off the value of movie.frameRate just after my first call to movie.read().

**Comment by codeanticode** [comment]
@krismz thanks for the observation. The documentation is a bit ambiguous on this, since while it does describe the [frameRate()](https://processing.org/reference/libraries/video/Movie_frameRate_.html) function, it does not make any reference to the frameRate variable. My interpretation is that it should contain wherever was last set with frameRate(), which is consistent with the usage of the [frameRate](https://processing.org/reference/frameRate.html) variable in PApplet.

@alignedleft @REAS do you have any comments? Should we add an entry for the frameRate variable in the video documentation? Should we start the original frame rate of the movie file somewhere?

**Comment by freefulltime** [comment]
Avdshare Video Converter will take change MP4 file frame rate as an example and it can also serve to change AVCHD, MTS, M2TS, MXF, XAVC, ProRes, MPG, AVI, FLV, MOV, WMV, MKV and almost all video format frame rates
